### ISSUE TITLE
OSCM Jenkins installer

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-jenkinsscripts#43]
### Summary ### 
Provide the OSCM Jenkins CI/CD pipeline installable from GitHub.

### Details ###
The motivation is enable contributors to participate with OSCM DevOps and provisioning tasks. Therefore we'll provide a set of playbooks which allow them to setup and configure the required infrastructure.
 The idea is to install a pre-configured Jenkins server and any number of agents (we start with 1) which are suitable running the here contained pipeline scripts.
 
### Acceptance criteria ### 
- [ ] build & push 
- [ ] pull & start
- [ ] publish
- [ ] WS E2E Tests - Internal
- [ ] Web UI E2E tests - Internal
- [ ] WS E2E Tests - OIDC
- [ ] Web UI E2E tests - OIDC
